---

# If using split groups, be sure to increase the status depth
status_depth: 3

projects:
  web:
    github: "cabify/lana-web"

groups:
  libs:
    repoman:
      github: "cabify/repoman"
      go: true
    go-couchdb:
      github: "cabify/go-couchdb"
      go: true
    commom:
      github: "cabify/lana-common"
      go: true

  # Split `.` into subdirectories: `platform/services`
  platform.services:
    ledger:
      github: "cabify/lana-services-ledger"
      docker: "lanadev/ledger"
      go: true
    signer:
      github: "cabify/lana-services-signer"
      docker: "lanadev/signer"
      go: true
